# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    # necessary for windows?
    shell: bash

jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x]
        OS: [ubuntu-latest,macos-latest,windows-latest]

    runs-on: ${{ matrix.OS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --include=dev
    - run: cd client && npm install --include=dev && cd ..
    - run: cd server && npm install --include-dev && cd ..
    - run: npm run test-compile
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
